### ISSUE TITLE
Error: fine_map() got an unexpected keyword argument 'prior_chisq'

### ISSUE THREAD

**Issue by henkt7** [konumat/Trans-Phar#4]
Hi, I'm running into an error related to the prior_chisq argument for fine_map(). Just installed, working with python 3.7.3. Any suggestions would be welcome!

          FOCUS v0.802
===================================
focus finemap
        ../Output/Schizo/Schizo_munge.sumstats.gz
        ../1000G_EUR_Phase3_plink/1000G.EUR.QC.1
        GTEx_Adipose_Subcutaneous.db
        --chr 1
        --tissue Adipose_Subcutaneous
        --p-threshold 1
        --locations /projects/transphar/Trans-Phar/focus/pyfocus/data/ld_blocks/grch37.eur.loci.bed
        --out ../Output/Schizo/TWASresults/GTEx_Adipose_Subcutaneous/GTEx_Adipose_Subcutaneous.chr1

Starting log...
[2023-05-29 18:00:53 - INFO] Preparing GWAS summary file
[2023-05-29 18:01:23 - INFO] Preparing reference SNP data
[2023-05-29 18:01:25 - INFO] Preparing weight database
[2023-05-29 18:01:25 - INFO] Preparing user-defined locations
[2023-05-29 18:01:25 - INFO] Prioritizing genes by Adipose_Subcutaneous tissue then on predictive performance at region 1:13110 - 1:1892325
[2023-05-29 18:01:25 - ERROR] fine_map() got an unexpected keyword argument 'prior_chisq'
[2023-05-29 18:01:25 - INFO] Finished twas & fine-mapping

**Comment by henkt7** [comment]
Update: as a test I ran focus outside of the Trans-Phar pipeline using the already cleaned tutorial Schizophrenia sumstats and the focus.db weight database (from https://github.com/bogdanlab/focus/wiki) and didn't run into the above error then. So, might be Trans-Phar pipeline where error arises? 

`focus finemap ../../Output/Schizo/Schizo_munge.sumstats.gz ../../1000G_EUR_Phase3_plink/1000G.EUR.QC.22 ../focus.db --chr 22 --locations /projects/transphar/Trans-Phar/focus/pyfocus/data/ld_blocks/grch37.eur.loci.bed --tissue adipose --out ../test_output/test_ch22`

**Comment by 1667857557** [comment]
> Update: as a test I ran focus outside of the Trans-Phar pipeline using the already cleaned tutorial Schizophrenia sumstats and the focus.db weight database (from https://github.com/bogdanlab/focus/wiki) and didn't run into the above error then. So, might be Trans-Phar pipeline where error arises?
> 
> `focus finemap ../../Output/Schizo/Schizo_munge.sumstats.gz ../../1000G_EUR_Phase3_plink/1000G.EUR.QC.22 ../focus.db --chr 22 --locations /projects/transphar/Trans-Phar/focus/pyfocus/data/ld_blocks/grch37.eur.loci.bed --tissue adipose --out ../test_output/test_ch22`

We have encountered the same error. Have you found a solution to the problem？

**Comment by shinichinamba** [comment]
It appears that the issue is not stemming from Trans-Phar itself but rather from the recent upgrade of FOCUS. 
The FOCUS group has recently established a new GitHub page and released the latest version, which unfortunately is not compatible with the previous version. 
Trans-Phar specifies an older version of FOCUS, so attempting to run Trans-Phar in an environment with a newer version of FOCUS installed will result in an error. 
To mitigate this, we recommend creating a separate environment for Trans-Phar using pyenv or other environment-management tools.

**Comment by 1667857557** [comment]
Thanks a lot!


> It appears that the issue is not stemming from Trans-Phar itself but rather from the recent upgrade of FOCUS. The FOCUS group has recently established a new GitHub page and released the latest version, which unfortunately is not compatible with the previous version. Trans-Phar specifies an older version of FOCUS, so attempting to run Trans-Phar in an environment with a newer version of FOCUS installed will result in an error. To mitigate this, we recommend creating a separate environment for Trans-Phar using pyenv or other environment-management tools.

**Comment by henkt7** [comment]
thanks @shinichinamba
Unfortunately, it looks like the same error occurs with the older FOCUS version as well (from https://github.com/bogdanlab/focus)
